from .clique_verify import verify_clique_solution
from .independent_set_verify import verify_independent_set_solution
from .vertex_cover_verify import verify_vertex_cover_solution
from .three_color_verify import verify_three_color_solution
